export const appName = 'Sabbath School'
export const appShortName = 'Sabbath School'
export const appDescription = 'Studying Sabbath School has never been easier. Now you can take your Sabbath School Bible study guide with you wherever you go.'
export const appImage = '/assets/images/cover.jpg'
export const appThemeColor = '#2E5797'
export const appUrl = 'https://sabbath-school-nuxt.vercel.app'
export const appGooglePlayName = 'Sabbath School & PM'
export const appGooglePlayId = 'com.cryart.sabbathschool'
export const appGooglePlayUrl = 'https://play.google.com/store/apps/details?id=com.cryart.sabbathschool'
export const appAppStore = 'https://apps.apple.com/us/app/sabbath-school/id895272167'
export const appAuthor = 'Adventech - https://adventech.io'
